config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"

  resources :posts
  resources :users do
    post :is_admin, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    class << self
        def markdown
            Redcarpet::Markdown.new(Redcarpet::Render::HTML)
        end
    end
    validates :title, :content, presence: true

    def self.search(search)
        if search
            Post.where('lower(title) LIKE lower(:search)', search: "%#{search}%")
        else
            Post.all
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 
            :presence => true, 
            :uniqueness => true, 
            :format => { with: VALID_EMAIL_REGEX }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    private
    
    def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
       devise_parameter_sanitizer.permit(:account_update, keys: [:name])
     end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, :except => [:index, :show]

    def index
        @posts = Post.search(params[:search]).order('created_at DESC').paginate(:page => params[:page], :per_page => 7)
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post
        else
            render "new"
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        if @post.save
            redirect_to @post
        else
            render "edit"
        end
    end

    def destroy
        @post = Post.find(params[:id])
        if @post.destroy
            redirect_to root_path
        else
            render @post
        end
    end

private
    def post_params
        params.require(:post).permit(:title, :content, :search)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action do 
        redirect_to posts_path unless current_user && current_user.admin?
    end

    def index
        @users = User.all
    end

    def is_admin
        @user = User.find(params[:id])
        @user.update(admin: true)
        redirect_to root_path
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path, notice: 'User deleted.'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'redcarpet'
  require 'rouge'
  require 'rouge/plugins/redcarpet'

  class HTML < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet
  end

  def rouge_markdown(text)
    render_options = {
        filter_html: true,
        hard_wrap: true,
        link_attributes: { rel: 'nofollow' }
    }
    renderer = HTML.new(render_options)

    extensions = {
        autolink: true,
        fenced_code_blocks: true,
        lax_spacing: true,
        no_intra_emphasis: true,
        strikethrough: true,
        superscript: true
    }
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono:400,700&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wrapper">
      <div class="search-group">
          <%= form_tag posts_path, method: :get do %>
          <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "Search posts...") %>
              <%= button_tag 'Search' %>
          <% end %>
      </div>
      <ul class="navbar-list">
        <li><%= link_to 'Posts', posts_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'New', new_post_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete  %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <div class="footer-wrapper">
      <ul class="footer-list">
        <li>© Dave Guymon, 2020</li>
      </ul>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="page-wrapper">

    <h2><%= title %> post</h2>

    <%= form_with model: @post, class: "form-wrapper" do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :content %>
        <%= f.text_area :content %>

        <%= f.submit %>
    <% end %>
</div>

app/views/posts/edit.html.erb
<%= render :partial => 'form', :locals => {title: 'Edit'} %>
<%= link_to 'Cancel', post_path(@post) %>

app/views/posts/index.html.erb
<div class="page-wrapper">
<%= will_paginate @posts %>
    <% @posts.each do |post| %>
        <div class="post-item-wrapper">
            <h1><%= link_to post.title, post_path(post.id) %></h1>
            <p><%= post.created_at.strftime("%B, %d, %Y")%></p>
            <p><%= truncate(rouge_markdown(post.content), length: 450, escape: false) { link_to "(continue)", post_path(post.id) } %></p>
        </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<%= render :partial => 'form', :locals => {title: 'Create'} %>

app/views/posts/show.html.erb
<div class="page-wrapper">
    <div class="post-wrapper">
        <h1><%= @post.title %></h1>
        <p><%= @post.created_at.strftime("%B, %d, %Y")%></p>
        <p><%= raw rouge_markdown(@post.content) %></p></br>
        <% if user_signed_in? %>
            <%= link_to 'Edit', edit_post_path(@post) %>
            <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="page-wrapper">
    <table class="user-wrapper">
        <thead>
            <tr>
                <th>Email</th>
                <th>Admin?</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
                <tr>
                    <td><%= user.email %></td>
                    <td><%= user.admin %></td>
                    <% if @users.count > 1 %>
                        <td><%= link_to 'Remove', user_path(user.id), :method => :delete %></td>
                    <% end %>
                    <% if !user.admin %>
                        <td><%= button_to 'Make admin', is_admin_user_path(user.id), :class => "admin-button" %></td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>